//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 11:24:33 AM CET 
//


package vehicle.tr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for connectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="connectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="node1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="node2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "connectionType", propOrder = {
    "node1",
    "node2"
})
public class ConnectionType {

    @XmlElement(required = true)
    protected String node1;
    @XmlElement(required = true)
    protected String node2;

    /**
     * Gets the value of the node1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode1() {
        return node1;
    }

    /**
     * Sets the value of the node1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode1(String value) {
        this.node1 = value;
    }

    /**
     * Gets the value of the node2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode2() {
        return node2;
    }

    /**
     * Sets the value of the node2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode2(String value) {
        this.node2 = value;
    }

}
