//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 11:24:33 AM CET 
//


package vehicle.tr;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vehicle.tr package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Path_QNAME = new QName("http://www.example.org/VehicleTracking", "path");
    private final static QName _Vehicle_QNAME = new QName("http://www.example.org/VehicleTracking", "vehicle");
    private final static QName _Graph_QNAME = new QName("http://www.example.org/VehicleTracking", "graph");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vehicle.tr
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PathType }
     * 
     */
    public PathType createPathType() {
        return new PathType();
    }

    /**
     * Create an instance of {@link PathResponse }
     * 
     */
    public PathResponse createPathResponse() {
        return new PathResponse();
    }

    /**
     * Create an instance of {@link GraphType }
     * 
     */
    public GraphType createGraphType() {
        return new GraphType();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link ParkingArea }
     * 
     */
    public ParkingArea createParkingArea() {
        return new ParkingArea();
    }

    /**
     * Create an instance of {@link Road }
     * 
     */
    public Road createRoad() {
        return new Road();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link PathType.Node }
     * 
     */
    public PathType.Node createPathTypeNode() {
        return new PathType.Node();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PathType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/VehicleTracking", name = "path")
    public JAXBElement<PathType> createPath(PathType value) {
        return new JAXBElement<PathType>(_Path_QNAME, PathType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VehicleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/VehicleTracking", name = "vehicle")
    public JAXBElement<VehicleType> createVehicle(VehicleType value) {
        return new JAXBElement<VehicleType>(_Vehicle_QNAME, VehicleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GraphType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/VehicleTracking", name = "graph")
    public JAXBElement<GraphType> createGraph(GraphType value) {
        return new JAXBElement<GraphType>(_Graph_QNAME, GraphType.class, null, value);
    }

}
