//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.13 at 05:02:48 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.vechicleTrackingSystem.org/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vehicle.tr;
