//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 11:24:33 AM CET 
//


package vehicle.tr;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for road complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="road">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/VehicleTracking}nodeType">
 *       &lt;sequence>
 *         &lt;element name="endPoint" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="maxVehicle" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "road", propOrder = {
    "endPoint",
    "maxVehicle"
})
public class Road
    extends NodeType
{

    protected boolean endPoint;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxVehicle;

    /**
     * Gets the value of the endPoint property.
     * 
     */
    public boolean isEndPoint() {
        return endPoint;
    }

    /**
     * Sets the value of the endPoint property.
     * 
     */
    public void setEndPoint(boolean value) {
        this.endPoint = value;
    }

    /**
     * Gets the value of the maxVehicle property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxVehicle() {
        return maxVehicle;
    }

    /**
     * Sets the value of the maxVehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxVehicle(BigInteger value) {
        this.maxVehicle = value;
    }

}
